sudo: false
language: rust
cache: cargo
rust:
- beta
- stable
- nightly
matrix:
  include:
  - rust: nightly-2017-10-09
    env: CLIPPY_VERS="0.0.165"
    before_script: |
      [[ "$(cargo +nightly-2017-10-09 clippy --version)" != "$CLIPPY_VERS" ]] && \
      cargo +nightly-2017-10-09 install clippy --vers "$CLIPPY_VERS" --force || true
    script: |
      cargo +nightly-2017-10-09 clippy -- -D warnings
  - rust: nightly-2017-10-09
    env: RUSTFMT_VERS="0.2.8"
    before_script: |
      [[ "$(cargo +nightly-2017-10-09 fmt -- --version)" != "$RUSTFMT_VERS"* ]] && \
      cargo +nightly-2017-10-09 install rustfmt-nightly --vers "$RUSTFMT_VERS" --force || true
    script: |
      cargo +nightly-2017-10-09 fmt --all -- --write-mode=diff
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  travis-cargo build &&
  travis-cargo clean &&
  travis-cargo test &&
  travis-cargo bench
notifications:
  email:
    on_success: never
branches:
  only:
    - master
    - staging
    - trying
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  - secure: OUHDuY7h82pYkis1oJW/dO029Rp/HLGT7od5VQJ1eki0M+Oawj7L0tjQPGLKLjj6hA1Sh8XeeelQgrlwVQfkrvwgYLRfmEdbP8z2PclmbxvXmRFysM5R9dN15HYx9AlUsDiHF9otmkNzJPBghlLvvKbzjp7Mlr5cdBaFZ9psafJLOgIWTIpiuHvYhmKhaXG6bIpLw6pi9NWdUYcd5s/gy1n1v5a4oPH/JB9V3Zc8+tv/EPvRynzSRK1jghD7KtppQoRRt92OCQGZ2BYLoTVpkt/bPS50D558xbVoDPyNNgcPM86eSSNbgp8llASJMFVNWWBZYLmbQ5x/219G907YbKWDLbcwMJL0H/JFbtErLarDU5XiEFBELs0Zx2t0S96xOM+ZWxZvWBk3UuKTBaXIKc921JEU+uHHUsPp3zasiMZWN3Rv2ia68HZGvYtwAPG5PWJTeh7BAo6dLGNDISVE/uHhf64E+ZvH3ToEmadx/yimedE7IOBh7kvPTnr1X5RFWNEJYOVSWJ531LoE3WHO9/UKPRLx01fGHzJKXMyWcp2fQjwCsu9zwThk3N4kYQJfi5YNmJw1EiOERiQ0nRckaUC5sA5KE+ZJmEa4ztfe7RMTVceCNagVdsqH8IHWgM+ROKNNKYDjqKbGSiE0RVwUdITUFLeQDWzQYfzsWRQpFV0=
